name: "\U0001F41E Report a problem"
description: File a bug report
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    attributes:
      label: What did you do?
      description: |
        If possible please include a *minimal* reproduction case with source code, configuration file, any other information about how you're using the gui. You can use Markdown in this field.
      value: |
        <details>
        <summary>Configuration</summary>

        ```
        <!-- Paste your configuration here -->
        ```
        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: |
        You can use Markdown in this field.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What actually happened?
    validations:
      required: true
    - type: dropdown
      id: browsers
      attributes:
        label: What browsers are you seeing the problem on?
        multiple: true
        options:
          - Firefox
          - Chrome
          - Safari
          - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
